services:
  s3:
    image: bitnami/minio:latest
    container_name: s3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "~/minio/data:/data"
    env_file: "./src/.env"
  
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - 8000:8000
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    env_file: "./src/.env"
    working_dir: "/home/dynamodblocal"

  weather-app:
    depends_on:
      - s3
      - dynamodb-local
    build: .
    ports:
      - 80:80
    env_file: "./src/.env"

networks:
  default:
    name: weather-app-network
